version: '3'

services:

  gotenberg:
    image: thecodingmachine/gotenberg:latest
    environment:
      - DEFAULT_GOOGLE_CHROME_RPCC_BUFFER_SIZE=10485760

  proxy:
      image: pottava/proxy
      ports:
        - "80:80"
      environment:
        - PROXY_URL=http://gotenberg:3000
        - BASIC_AUTH_USER=admin
        - BASIC_AUTH_PASS=password

